import React from 'react';
import { BusinessListing, Lead } from '../types';

interface AdminDashboardProps { pendingBusinesses: BusinessListing[]; activeBusinesses: BusinessListing[]; adminLeads: Lead[]; onApproveBusiness: (id: string) => void; onRejectBusiness: (id: string) => void; onInspectBusiness: (business: BusinessListing) => void; onOpenAddCategory: () => void; onExportData: () => void; onSelectLead: (lead: Lead) => void; onViewAllPending: () => void; }

export const AdminDashboard: React.FC<AdminDashboardProps> = ({ pendingBusinesses, activeBusinesses, onApproveBusiness, onRejectBusiness, onInspectBusiness, onViewAllPending }) => {
  const allBusinesses = [...pendingBusinesses, ...activeBusinesses];
  const categories = allBusinesses.reduce<Record<string, number>>((counts, business) => ({ ...counts, [business.category]: (counts[business.category] || 0) + 1 }), {});
  return <main className="mx-auto w-full max-w-7xl space-y-5 px-4 pb-24 pt-5 sm:px-6 lg:px-8 md:pb-8">
    <div><h2 className="text-[24px] font-bold">Directory overview</h2><p className="text-[13px] text-[#4a4455]">Live data from the business API.</p></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Stat label="All listings" value={allBusinesses.length} icon="business" /><Stat label="Published" value={activeBusinesses.filter(item => item.status === 'Active').length} icon="verified" /><Stat label="Awaiting review" value={pendingBusinesses.length} icon="pending_actions" /></div>
    <section className="rounded-xl border border-[#ccc3d7] bg-white p-4"><h3 className="text-[16px] font-bold">Listings by category</h3>{Object.keys(categories).length ? <div className="mt-3 flex flex-wrap gap-2">{Object.entries(categories).map(([name, count]) => <span key={name} className="rounded-full bg-[#ebdcff] px-3 py-1 text-[12px] font-semibold text-[#5300b7]">{name}: {count}</span>)}</div> : <p className="mt-2 text-[13px] text-[#7b7486]">No listings available.</p>}</section>
    <section className="rounded-xl border border-[#ccc3d7] bg-white p-4"><div className="flex items-center justify-between"><h3 className="text-[16px] font-bold">Pending approval</h3><button onClick={onViewAllPending} className="text-[13px] font-semibold text-[#5300b7]">View all</button></div>{pendingBusinesses.length ? <div className="mt-3 space-y-3">{pendingBusinesses.slice(0, 5).map((business) => <div key={business.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-[#f0edf1] pt-3"><button onClick={() => onInspectBusiness(business)} className="text-left"><strong className="block text-[13px]">{business.name}</strong><span className="text-[12px] text-[#7b7486]">{business.owner} · {business.category}</span></button><div className="flex gap-2"><button onClick={() => onRejectBusiness(business.id)} className="rounded-lg border border-[#ccc3d7] px-3 py-1.5 text-[12px] font-semibold text-red-700">Reject</button><button onClick={() => onApproveBusiness(business.id)} className="rounded-lg bg-[#5300b7] px-3 py-1.5 text-[12px] font-semibold text-white">Approve</button></div></div>)}</div> : <p className="mt-2 text-[13px] text-[#7b7486]">No listings are waiting for review.</p>}</section>
  </main>;
};

const Stat = ({ label, value, icon }: { label: string; value: number; icon: string }) => <div className="rounded-xl border border-[#ccc3d7] bg-white p-4"><span className="material-symbols-outlined text-[#5300b7]">{icon}</span><p className="mt-2 text-[30px] font-bold leading-none">{value}</p><p className="mt-1 text-[12px] text-[#7b7486]">{label}</p></div>;
