import React, { useState } from 'react';
import { updateOwnerBusiness } from '../api';
import { BusinessListing } from '../types';

export const OwnerBusinessEditor = ({ business, onClose, onSaved }: { business: BusinessListing; onClose: () => void; onSaved: (business: BusinessListing) => void }) => {
  const [description, setDescription] = useState(business.description || ''); const [phone, setPhone] = useState(business.phone === 'Not added' ? '' : business.phone); const [city, setCity] = useState(business.location === 'Location not added' ? '' : business.location); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const updated = await updateOwnerBusiness(business.id, { description: description || undefined, phone: phone || undefined, address: city ? { city } : undefined }); onSaved(updated); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save profile'); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold">Complete business profile</h2><p className="text-sm text-slate-500">Save whenever you are ready; only information you provide is updated.</p></div><button type="button" onClick={onClose}>Close</button></div>{error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 space-y-4"><label className="block text-sm font-medium">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} className="mt-1 min-h-28 w-full rounded-lg border border-slate-300 p-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Phone<input value={phone} onChange={(e) => setPhone(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">City / location<input value={city} onChange={(e) => setCity(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label></div><p className="text-xs text-slate-500">For review submission, your API requires a description, phone, address line 1, and map coordinates.</p></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancel</button><button disabled={saving} className="rounded-lg bg-violet-700 px-4 py-2 font-semibold text-white">{saving ? 'Saving…' : 'Save changes'}</button></div></form></div>;
};
